name: Futureblog
favicon: null
layout_spectrum: 0.5540513854939491
typography_spectrum: 0.6150672489311546
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8019267579074949
  lightness: 0.8888401000294834
  saturation: 0.0008042396511882544
  rhythmicContrast: 0.5505699112545699
purpose: []
